### ISSUE TITLE
Way too small in IVA

### ISSUE THREAD

**Issue by njbrown09** [Vivero/Kerbal-VR#31]
You cant read anything. JSI panels feel like they are only 4x4 inches

**Comment by Vivero** [comment]
Yea I think they literally are lol. Everything in RPM seems to be miniaturized, jrbudda had a code change to make the world scale adjustable. I'll pull that in; might be the only way to make the screens readable, but it also might make the cockpits seem a little big.

**Comment by jrbudda** [comment]
I (or you) need to re-do that code since it doesn't adjust the controller positions, just hmd. 

Kerbals are like 2 feet tall so using real 1:1 scale.. yea.. those things are tiny. I found about 1.75x scale to be about right for the props of the pod, tho kerbals have such odd proportions you basically sit in just the kerbal's helmet at that size.

Been working on a large update for KER and haven't had a chance to play with VR.

**Comment by Vivero** [comment]
Makes sense. I'll work up a fix for it, thanks!

**Comment by Vivero** [comment]
Closed via #32
