### ISSUE TITLE
Oculus Rift - hands/controllers aren't visible

### ISSUE THREAD

**Issue by finlopes97** [Vivero/Kerbal-VR#48]
The controls appear to work, as I was able to navigate the staging area using the analog sticks on the Touch controllers. However my "VR Hands" do no appear, despite the controllers being on and detected by the Steam VR interface.

**Comment by Vivero** [comment]
I'm not sure... I don't have a Rift/Touch to test with. Maybe if you post a copy of the KSP.log, there may or may not be information there to help

**Comment by ghost** [comment]
Hi! Someone else with a Rift+Touch here. Here's my KSP.log: 
[KSP.log](https://github.com/Vivero/Kerbal-VR/files/2156850/KSP.log)

**Comment by Vivero** [comment]
Thanks @steamp0rt I think I see something wrong in the log. I'll try to come up with a fix soon, but in the meantime could you try the following?
Before you start up KSP, turn off the Touch controllers. Then start KSP, load your game, etc. _Then_ turn on the Touch controllers. When you go into VR, I think hopefully you should see the hands.

I don't have a Touch, so I can't test this exactly, but I know you can do this with the Vive wands (keep them off until after I've loaded KSP, then turn them on).

I think the underlying problem here is having the controllers on during KSP start up, during which the glove models haven't been loaded into the game.

**Comment by SolidJuho** [comment]
Hey, I tried turning touch controllers on after loading game save, but I am still unable to see my hands.

[output_log.txt](https://github.com/Vivero/Kerbal-VR/files/2516288/output_log.txt)

**Comment by enriquesaou** [comment]
I am on WMR and i experience the same problem, i cant see my hands, even though they are there (i can interact with RPM) I hope there is a solution

**Comment by Vivero** [comment]
I believed I fixed this in the new release: https://github.com/Vivero/Kerbal-VR/releases/tag/v3.2.4

**Comment by Vivero** [comment]
Closed via #77
