### ISSUE TITLE
Control MFDs in VR

### ISSUE THREAD

**Issue by Poldor** [Vivero/Kerbal-VR#5]
Once in VR, there is no way to control the rpm mfd pages. Some sort of UI would be needed for this.

**Comment by robotnia** [comment]
The mouse cursor dissapears on VR. It would be really nice to have someway to control the MFD from RasterPropMontitor and have an total imersive VR experience. Anyway great job. I´m very happy to see this project still alive and I´m looking forward for new updates. Thank you

**Comment by Vivero** [comment]
I'm a big fan of RasterPropMontitor, I also really want to focus on VR interactions with the cockpit. I've experimented with trying to integrate VR with RasterPropMontitor, but it's looking pretty difficult. I'm inclined to say trying to emulate mouse clicks with a VR controller is not looking like the way to go.

As much as I would love to re-use the entirety of the RPM mod (because it has so many good features already), it may make more sense to roll out my own version of an IVA cockpit mod within KerbalVR; one that is more appropriate for interactions in VR (i.e. flipping a switch requires an actual flipping gesture with your remote, and not just a button press on the remote).

Anyways these are just my current thoughts, stay tuned! Thanks for following along.

**Comment by Poldor** [comment]
First thank you very much for the great implementation in 1.4, escpacially with the very good performance. Playing KSP in VR is now just like I wanted it to be for ages.

Did you already try out the very intresting RPM follow-up mod by Moardv?
https://github.com/MOARdV/AvionicsSystems

It seems to me, the perfomance impact on the fps is much lower.

A special VR IVA Cockpit mod seems to be a great idea (I guess you have something like VTOL VR in mind?), but also like a great endavour.
I already startet to mod the RPM cockpits to make them more readable in VR (basicly just increasing the size of monitors and removing the not usable clickable props) like this:
![image](https://user-images.githubusercontent.com/20559630/37790467-eb02567a-2e06-11e8-9f7d-f304196a03d0.png)

Do you plan of implementing an adjustable scalefactor, as the "small size" of the cockpit makes reading the monitors almost impossible?
If you plan to make VR cockpit props I could definitely help you by populating all the stock IVAs with them.

Keep up the good work and thanks again!

**Comment by Vivero** [comment]
AvionicsSystems does look promising; I'm not 100% convinced yet, I've looked at some of the code. I _think_ it would have the same implications as RPM, i.e. not sure how I can "hook" in VR interactions.
It's architecture does seem more performant than RPM, but I'm also a little concerned with its implementation of Lua-based scripting. I'm wondering if having that layer of an interpreted language to carry out flight computations every frame might bog down VR performance. I feel like pushing 90 FPS to the Vive is difficult enough as it is.
I'll keep an eye on Moardv's mod and keep thinking about it some more as the KerbalVR project develops.

**Comment by Vivero** [comment]
To address your other points, yes having an adjustable scale factor is probably a good idea, and maybe not hard to implement (@jrbudda just made a pull request with this functionality).

For the immediate future I'm going to incorporate just a few of ASET Prop's components that are interactive in VR. And in this case, I could definitely use some help coming up with new VR-friendly IVA's (that pic looks really great, good job!).

**Comment by Vivero** [comment]
Version 3.1.0 of the mod now implements interaction with RPM instruments! Thanks @jrbudda for helping with this.

Closing this issue for now, but I will continue to add features that implement "VR-friendly" props inside IVA.

**Comment by Vivero** [comment]
Closed via #27
