### ISSUE TITLE
Crashing as soon as I get to loading.

### ISSUE THREAD

**Issue by wal310** [Vivero/Kerbal-VR#64]
CTD as soon the loading icon appears the game crashes. Have the old version of ksp installed and module manager and the shortcut and still crashes.

**Comment by Vivero** [comment]
Describe the bug A clear and concise description of what the bug is.

To Reproduce Steps to reproduce the behavior:

Go to '...'
Click on '....'
Scroll down to '....'
See error
Expected behavior A clear and concise description of what you expected to happen.

Log Attach a copy of the KSP.log file.

Screenshots If applicable, add screenshots to help explain your problem.

Desktop (please complete the following information):

OS: [e.g. Windows 10]
KSP Version: [e.g. 1.4.5]
VR Hardware: [e.g. Vive]
Kerbal-VR Version: [e.g. 3.2.1]
Additional context Add any other context about the problem here.
