### ISSUE TITLE
Confirmed to work with Rift S?

### ISSUE THREAD

**Issue by RevBrockly** [Vivero/Kerbal-VR#84]
I am having WILD flickering\shakes whenever i move my head despite follow all the graphic and installation instructions.  Such a promising mod but nauseating at this point.  While sitting on the runway at KSC the Mun especially spazes out whenever I move my head.  I have an FX-8320, Nvidia GTX 1660, 16 GB of RAM.
[KSP.log](https://github.com/Vivero/Kerbal-VR/files/3543245/KSP.log)

**Comment by Vivero** [comment]
I don't have a Rift S to test with, so technically I'm not sure how the mod would perform. However I've noticed in the past year or so, the mod's VR performance has tanked, without me having made any changes to the code (or the hardware that I test with). Which makes me think maybe Squad has made changes to the game that affects performance...
Anyways, wasn't sure if other people noticed this too, sounds like you certainly have because those are pretty decent PC specs. I don't think even I can currently achieve 90fps anymore as I advertised in the front page (it definitely was possible in the past). I'm gonna have to change that, so people are aware of the current limitations.
Not sure what I can do at this point to improve performance, I need some time to think about it.

**Comment by Igglebork** [comment]
I can confirm I get lots of shaking when moving my head on the Rift S as well, also noted mun bouncing around.

I tried updating the openvr dll but it didn’t seem to make a difference.

PC specs are i5-7500, 32gb ram, GTX 1060.

**Comment by Rushyo** [comment]
This doesn't seem like a performance issue; it's kinda like... micro-movements of the head being translated to the world origin. Even Kerbin bounces around with the shakes, which doesn't make any sense to me if it was a perf or mistranslation issue.

**Comment by Vivero** [comment]
I don't really know what the original issue here was, but if this is what you're talking about:

> Even Kerbin bounces around with the shakes

Then I believe I might've fixed that in the [latest release](https://github.com/Vivero/Kerbal-VR/releases/tag/v3.2.6)
